### ISSUE TITLE
Integration with SDL1/2?

### ISSUE THREAD

**Issue by a-hurst** [jwwalker/Quesa#1]
Hi there,

Glad to see this is still getting maintained! A long-time "someday" project for me has been to take the Nanosaur source code and write some glue code to get it running natively on modern computers, and since Nanosaur is heavily based on the QD3D API, any attempt at a port is going to need to be based around Quesa. I'm finally getting to the point where I have enough C experience from other projects that I might actually be able to tackle this.

My question is: is it possible for me to create an OpenGL context with a different library (SDL1 or 2) and then pass that GL context on to Quesa so it knows to render to it? I'd imagine it's probably possible, but reading through the code examples and API docs I'm not seeing an easy way to do this. If it's possible, could you please point me to the right place in the code or docs to look? If I can get a minimal example up and running, I'd be happy to contribute it via a PR.

Thanks in advance!

**Comment by jwwalker** [comment]
I don't really know anything about SDL other than the fact that it's a cross-platform library.  Presumably it's implemented using native capabilities of each platform, e.g., NSView on macOS.  So I think what you'd have to do is see whether SDL has APIs that will reveal the underlying platform-specific constructs, and them pass them to Quesa.

**Comment by a-hurst** [comment]
I think you can probably get at the underlying windowing stuff with some platform-specific hacks, but it makes portability a pain.

Is the issue just that the window/context creation code and rendering code in Quesa are intertwined in a way that makes it hard to use Quesa’s OpenGL renderer with a window and context created by a different library? If that’s the case I might attempt writing an SDL platform back-end for Quesa: glancing through the source, it looks
like the main platform-specific code is found in the `Development/Source/Platform` directory and get wrapped in various parts of `Development/Source/Core`. A lot of the stuff getting wrapped (draw context creation, file handling, logging, etc.) is stuff that SDL already wraps cleanly anyway, so it’d just be mapping the APIs onto eachother. Are there any major pitfalls or quirks I should watch out for if attempting to add a new platform backend?

**Comment by jwwalker** [comment]
Quesa has a different draw context class for each kind of platform view/window, so one task would be to create a new draw context class.  But the more involved thing is letting the renderer know how to deal with each draw context class. See particularly the file GLDrawContext.cpp.  For instance you'll find the function GLDrawContext_New, which looks at what kind of draw context it's dealing with and then figures out how to create an OpenGL drawing context.

**Comment by jwwalker** [comment]
SDL is not currently a priority for me, but there is some SDL support in [Jorio's fork](https://github.com/jorio/Quesa).
