### ISSUE TITLE
___isPlatformVersionAtLeast link error with old Xcode due to @available 

### ISSUE THREAD

**Issue by seanm** [jwwalker/Quesa#10]
If I build Quesa, then use the result with older Xcodes, I get a link error:

```
  "___isPlatformVersionAtLeast", referenced from:
      -[QuesaViewWatcher refreshCachedBounds] in libQuesa.a(E3CocoaDrawContext.o)
      e3drawcontext_cocoa_get_dimensions(OpaqueTQ3Object*, TQ3Area*) in libQuesa.a(E3CocoaDrawContext.o)
ld: symbol(s) not found for architecture x86_64
```

This seems to be a well-known limitation/bug of Xcode. 

Easy solution: replace the 4 uses of `if (@available( macOS 10.15, * ))` with `if (floor(NSAppKitVersionNumber) >= 1894.0)`

All 4 guard the use of `convertRectToBacking:`, but that API was added in 10.7.  Is the 10.15 check wrong, should it be 10.7?

**Comment by jwwalker** [comment]
How old a version of Xcode are we talking?  I didn't think `@available` was a particularly recent feature.  I'm reluctant to change it, as that seems like the approach that Apple always recommends.  It's also easier to read than some weird AppKit version number.

Checking for 10.15 instead of 10.7 is deliberate.  Although `convertRectToBacking` may have worked earlier, it wasn't necessary until a change in the implementation of `NSOpenGLView` in Catalina.

**Comment by seanm** [comment]
Xcode 10.1, the newest possible on macOS 10.13.x, released 2018-10-30.

It's not that Xcode 10.1 doesn't support `@available`, it's that building a lib on a newer Xcode, then using that lib with an older Xcode fails.  Others have the same issue, ex: https://developer.apple.com/forums/thread/123003

In my case, to build Quesa as a fat binary, I have to use Xcode 12. Since Quesa changes rarely, I commit the resulting libQuesa.a to my source control, then bots of several versions of macOS build my own code nightly against it.

**Comment by seanm** [comment]
Here's a fix: https://github.com/jwwalker/Quesa/pull/11

**Comment by jwwalker** [comment]
I pushed a revision that puts the version test in a new function, so that I can document it in one place.  By the way, the use of the `floor` function in your pull request was unnecessary.

**Comment by seanm** [comment]
Thanks!

`floor`ing `NSAppKitVersionNumber` is idiomatic, and old habits die hard. :)
