### ISSUE TITLE
nullability annotation missing on TQ3MacOSDialogEventHandler & TQ3DialogAnchor

### ISSUE THREAD

**Issue by seanm** [jwwalker/Quesa#3]
I've rebuilt Quesa and now building my own app gives 2 nullability warnings from Quesa headers: 

```
QuesaRenderer.h:1272:49: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
QuesaRenderer.h:1287:5: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
```

I can make a PR but @jwwalker you'd know better than me if this should be nullable or nonnull.

**Comment by jwwalker** [comment]
@seanm That code is subject to `#if QUESA_OS_MACINTOSH && ! QUESA_OS_COCOA`, which means it can be considered vestigial.  We don't really have a non-Cocoa Mac implementation any more.  So maybe we should just remove such things.

**Comment by seanm** [comment]
I am on Mac, but I also set QUESA_OS_COCOA=0 because all I really use Quesa for is reading 3dmf files, so I try to pull in as few dependencies as possible (I don't even need any draw contexts for example).

**Comment by jwwalker** [comment]
Hmm.  I actually have a similar situation where I am experimenting with using Filament for rendering, which is why I introduced a generic draw context.  Maybe there should be a generic "platform" choice.

**Comment by seanm** [comment]
Wouldn't it be easiest to just throw on a `_Nonnull`, `_Nullable`, or even `_Null_unspecified` (if we can't be bothered to know if null is allowed or not)?

**Comment by jwwalker** [comment]
Done.  But I'll keep the idea of a generic platform, and cleaning out vestiges of pre-Cocoa Mac, in mind for when I have some time.

**Comment by seanm** [comment]
Sweet! Thanks!
